// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEub2JvwA7GiKcOm89jUPjckpoyq-UFwQ',
    appId: '1:1065421374828:android:e2ff1d8586f9a9baad5f49',
    messagingSenderId: '1065421374828',
    projectId: 'chat-app-50923',
    storageBucket: 'chat-app-50923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuO3CY4XZY4HQuXj5zjAfdOXsfc_QkjU',
    appId: '1:1065421374828:ios:fae0252fa07adf14ad5f49',
    messagingSenderId: '1065421374828',
    projectId: 'chat-app-50923',
    storageBucket: 'chat-app-50923.appspot.com',
    androidClientId: '1065421374828-47m9ts94l3kgdrg9cvfmnh8pghht09mr.apps.googleusercontent.com',
    iosClientId: '1065421374828-s4qdf6qgfnpmm35mc32jsrr0dl4nk55e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
